travis:
  secure:
    BINSTAR_TOKEN: nEA5u28S0EoShpMEN+m+AiC+fFdi/sR/kyIGvNNgu4Bm9DI2fBX9gnGFytWQai3J1TI0j6otKOjz2iwJnvqDgbl+IkoS2kUlosXE5EymmIiM7OhWZoPXOLLuauEesrPQOnT0RcXEWGuVFwpxw5n0zcCgji8R5SkaETHs+PkYegeTZFx8Bc5j1hmtHXPngOLhT/aF5775wkE03HprNNB3rtysBx8GNbA8fwEMg0Vvqndf+axtcpDoCKivs3IH0TJCMpssKu24XkGzwOxV7peiiFpXLrCH31pFrWvb0gCDbuizWLcPYonU1n5imAa3i/k11nKjnI70haeaw7lZFxxQtu8M0ABzFf0GGYrUGNndOs7tVVVMsyMkQkDZxROVlXajYlXRWoMQubmMZCq2YNS2tNQlFJMCkqRFmC+0tayW9pJdl3Cs4Ki/AC6KeU2I/9Eh6tC74PVTPU06mcK4HU95zKuQp8U7zp0mXlOwMUcmf9bFNNYM8oXUtFXVV19/8XJPqTGVGWPeEwUoKTxjULVTleELEW9Rs8jWbRkscuIOAsXuGy8uF6ncMYOYCL+zJDUxK9wqpT5a+WXFatQ0o2zM7ORQju+SpfstP4Zk8Poh+RhdrjZTGlgEeE4UB4wMuh3PNukoXmvijwHSziCIkvlkaZAixzHZxZO4iruuIYcC14o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
